CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(120) UNIQUE NOT NULL,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50), 
    password TEXT,
    country TEXT,
    currency VARCHAR(5) NOT NULL DEFAULT 'CAD',
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    accountName VARCHAR(50) NOT NULL,
    accountNumber VARCHAR(50) NOT NULL,
    accountBalance MONEY NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    description TEXT NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'Pending',
    amount MONEY NOT NULL,
    type VARCHAR(10) NOT NULL DEFAULT 'income',
    transactionDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);