CREATE TABLE User (
    id SERIAL PRIMARY KEY,
    email VARCHAR(120) UNIQUE NOT NULL,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50), 
    password TEXT,
    country TEXT,
    currency VARCHAR(5) NOT NULL DEFAULT 'CAD',
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Account (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES User(id),
    accountName VARCHAR(50) NOT NULL,
    accountNumber VARCHAR(50) NOT NULL,
    accountBalance NUMERIC NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Transaction (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES User(id),
    description TEXT,
    status VARCHAR(10) NOT NULL DEFAULT 'Pending',
    amount NUMERIC NOT NULL,
    type VARCHAR(10) NOT NULL DEFAULT 'income'
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);